name: tests
'on':
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-24.04
    name: Node ${{ matrix.node }}
    strategy:
      matrix:
        node:
          - "18"
          - "20"
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: sudo add-apt-repository -y ppa:inkscape.dev/stable && sudo apt-get install -y libcairo2-dev libjpeg8-dev libgif-dev optipng pngcrush pngquant libpango1.0-dev graphicsmagick libjpeg-turbo-progs inkscape gifsicle
      - run: npm install
      - run: npm test

  test-targets:
    runs-on: ubuntu-24.04
    name: ${{ matrix.targets.name }}
    strategy:
      matrix:
        targets:
          - name: 'Lint'
            target: 'lint'
          - name: 'Coverage'
            target: 'coverage'
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '18'
      - name: Install dependencies
        run: sudo add-apt-repository -y ppa:inkscape.dev/stable && sudo apt-get install -y libcairo2-dev libjpeg8-dev libgif-dev optipng pngcrush pngquant libpango1.0-dev graphicsmagick libjpeg-turbo-progs inkscape gifsicle
      - run: npm install
      - run: npm run ${{ matrix.targets.target }}
      - name: Upload coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ matrix.targets.target == 'coverage' }}
